apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis
  name: redis
spec:
  containers:
    - name: redis
      image: redis:3
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.25"
          mem: "64"
